# Generated by Django 5.1.3 on 2024-11-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название фильма')),
                ('short_description', models.TextField(verbose_name='Описание фильма')),
                ('text', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
